from typing import Any


def get_workflow_registry() -> dict[str, Any]:
    flows = [
        {
            "id": "source_intake",
            "name": "Source Intake Flow",
            "owner": "김지환",
            "status": "implemented",
            "purpose": "Notion, GitHub, Slack, Linear, MCP, 파일 입력을 공통 문서 입력 형식으로 정규화해요.",
            "entrypoint": "app/api/documents.py",
            "workflow_file": "app/workflows/source_intake.py",
            "nodes": ["validate_input", "select_connector", "fetch_external_content", "normalize_document", "finalize"],
            "input_contract": "source_type, source_url, external_id, title, content",
            "output_contract": "filename, content, source_type, source_url, external_id, document_type, fetched_via",
            "notes": "pasted/export content를 우선하고, 내용이 비어 있으면 서버 토큰 기반 connector로 자동 fetch해요.",
        },
        {
            "id": "storage_preprocessing",
            "name": "Storage Preprocessing Flow",
            "owner": "윤영준",
            "status": "implemented",
            "purpose": "원본 저장, chunk 분리, 재사용 chunk 필터링, Knowledge Card 추출을 실행해요.",
            "entrypoint": "app/api/documents.py",
            "workflow_file": "app/workflows/storage.py",
            "nodes": ["save_raw_document", "chunk_document", "extract_cards", "finalize"],
            "input_contract": "workspace_id, filename, content, source metadata",
            "output_contract": "document_id, chunk_count, card_count, skipped_chunk_count, new_card_ids, needs_review_count",
            "notes": "문서 저장 API가 호출하는 실제 LangGraph flow예요. 신규 카드 ID를 relation/review flow에 넘길 수 있게 반환해요.",
        },
        {
            "id": "relation_linking",
            "name": "Relation Linking Flow",
            "owner": "이용준",
            "status": "extension_slot",
            "purpose": "신규 카드와 기존 카드 사이의 중복, 관련, 충돌, 근거 관계를 후보로 연결해요.",
            "entrypoint": "app/services/relations.py",
            "workflow_file": "app/services/relations.py",
            "nodes": ["CandidateRelationDetector", "RelationLinkingService"],
            "input_contract": "new_cards, existing_cards, workspace_id",
            "output_contract": "relation candidates",
            "notes": "현재는 local candidate service로 동작하고, remote assistant로 교체 가능한 service boundary를 둬요.",
        },
        {
            "id": "retrieval_qa",
            "name": "Retrieval Q&A Flow",
            "owner": "이진우",
            "status": "implemented",
            "purpose": "질문 의도 분석, 카드/chunk 검색, relation 1-hop context, remote Q&A assistant 호출 상태를 관리해요.",
            "entrypoint": "app/api/search.py, app/api/qa.py",
            "workflow_file": "app/workflows/qa.py",
            "nodes": ["analyze_question", "retrieve_context", "expand_one_hop_relations", "generate_answer"],
            "input_contract": "workspace_id, question",
            "output_contract": "answer, confidence, evidence_cards, evidence_chunks, missing_evidence",
            "notes": "Q&A와 LLM Search API가 검색 근거를 remote LangGraph assistant에 보내고, 연결이 없으면 상태를 알려줘요.",
        },
        {
            "id": "quality_review",
            "name": "Quality Review Flow",
            "owner": "조은성",
            "status": "implemented",
            "purpose": "근거 부족, confidence low, needs_review 카드를 모아 검토 후보를 만들어요.",
            "entrypoint": "app/api/reviews.py",
            "workflow_file": "app/workflows/quality_review.py",
            "nodes": ["collect_candidates", "analyze_cards", "update_statuses", "generate_summary"],
            "input_contract": "workspace_id",
            "output_contract": "total_cards, reviewed_count, review_targets, quality_summary",
            "notes": "POST /api/workspaces/{workspace_id}/reviews/run 으로 실행해요. LLM 없이도 규칙 기반으로 동작해요.",
        },
    ]
    links = [
        {"source": "source_intake", "target": "storage_preprocessing", "label": "normalized document"},
        {"source": "storage_preprocessing", "target": "relation_linking", "label": "new cards"},
        {"source": "relation_linking", "target": "retrieval_qa", "label": "graph context"},
        {"source": "retrieval_qa", "target": "quality_review", "label": "answer evidence"},
    ]
    return {
        "version": "2026-05-05",
        "runtime": "LangGraph StateGraph",
        "policy": "외부 LangGraph graph는 FastAPI adapter에서 호출하고, 앱 내부 flow는 검색과 저장 순서를 관리해요.",
        "flows": flows,
        "links": links,
    }
